[package]
name = "rapiddb"
version = "0.1.0"
edition = "2021"
default-run = "rapiddb"

[features]
default = []
full = ["db", "api"]
db = []
api = []

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = "1.0"
memmap2 = "0.5"
serde_json = "1.0"
redis = "0.21"
mysql = "22.1"

[lib]
#doctest = false
