[workspace]
resolver = "2"

members = [
  "rapiddb",
  "rapiddb-web",

  # Internal
  "examples",
]

[workspace.lints.rust]
unused_parens = "allow"

[workspace.lints.clippy]
needless_return = "allow"
