FROM docker.io/ubuntu:22.04
RUN apt-get update && apt-get install -y redis mysql-server && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/src/app
RUN sed '/bind-address/ s/^#*/#/' -i /etc/mysql/mysql.conf.d/mysqld.cnf
RUN sed 's/# max_connections        = 151/max_connections = 1000/' -i /etc/mysql/mysql.conf.d/mysqld.cnf
CMD service mysql start && redis-server --protected-mode no --databases 100
