FROM docker.io/ubuntu:22.04
RUN apt update
RUN apt install -y redis mysql-server
WORKDIR /usr/src/app
RUN sed -e '/bind-address/ s/^#*/#/' -i /etc/mysql/mysql.conf.d/mysqld.cnf
CMD service mysql start && redis-server --protected-mode no --databases 100
